version: "3.9"
services:
  src:
    build: .
    image: sports-complex
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"